sudo: true
language: node_js
env:
  global:
    - FF_BETA_PATH: './firefox/firefox'
cache:
  directories:
    - node_modules
node_js:
  - 'stable'
addons:
  # You can't install latest and beta as addons
  firefox: latest
  # Current broken on Travis 15/March/2016
  #apt:
  #  sources:
  #    - google-chrome
  #  packages:
  #    - google-chrome-stable
  #    - google-chrome-beta

before_install:
  # Chrome Stable
  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  - echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq
  - sudo apt-get install -y google-chrome-stable

  # Beta currently has dependencies that can't be met
  # - sudo apt-get install -y google-chrome-beta

  # Get firefox beta and extract to tar for the test runner to use.
  - wget 'https://download.mozilla.org/?product=firefox-beta-latest&lang=en-US&os=linux64' -O firefox-beta.tar.bz2 && tar xvjf firefox-beta.tar.bz2

install:
  - npm install

# Read more here: https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

script:
  - npm run build
  - npm run test
  - sh ./project/publish-docs.sh master
